version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - consumer
      - producer1
      - producer2
    networks:
      - lab2network

  producer1:
    build:
      context: ./producer1
      #no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2network

  producer2:
    build:
      context: ./producer2
      #no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2network

  consumer:
    build:
      context: ./consumer
      #no_cache: true
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: '0.5'

networks:
  lab2network:
